name: wikipedia_client
description: Wikipedia Client Mobile (Flutter + Wikipedia REST & Action API)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.2.7

  # HTTP
  dio: ^5.7.0

  # WebView 
  webview_flutter: ^4.8.0

  # Image cache 
  cached_network_image: ^3.4.1

  # Skeleton effect 
  shimmer: ^3.0.0

  # Storage
  shared_preferences: ^2.3.2

  # Text to Speech
  flutter_tts: ^4.0.2

  # Local DB for Offline/History/Cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4      

  # Support detecting online/offline status to select the data source
  connectivity_plus: ^6.0.5

  # Process HTML (extract summary, strip tags, etc.).
  html: ^0.15.4

  # Share link + open article in browser
  share_plus: ^12.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Create TypeAdapter for Hive (Article, HistoryEntry, CacheMeta)
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true

