name: wikipedia_client
description: Wikipedia Client Mobile (Flutter + Wikipedia REST & Action API)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.2.7

  # HTTP
  dio: ^5.7.0

  # WebView
  webview_flutter: ^4.8.0

  # Image cache (sẽ dùng khi hiển thị thumb)
  cached_network_image: ^3.4.1

  # Skeleton effect (tùy chọn)
  shimmer: ^3.0.0

  # Storage
  shared_preferences: ^2.3.2
  
  # Text to Speech
  flutter_tts: ^4.0.2
  
  # (Dự phòng cho các nhiệm vụ sau)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  # Nếu bạn có asset, khai báo ở đây:
  # assets:
  #   - assets/
